#!/command/with-contenv bash
# shellcheck shell=bash

if find /run/s6/container_environment/FILE__* -maxdepth 1 > /dev/null 2>&1; then
    for FILENAME in /run/s6/container_environment/FILE__*; do
        SECRETFILE=$(cat "${FILENAME}")
        if [ -f ${SECRETFILE} ]; then
            FILESTRIP="$(echo ${FILENAME} | sed 's|FILE__||')"
            if [ $(tail -n1 "${SECRETFILE}" | wc -l) != 0 ]; then
                echo "[init-envfile] Your secret: $(basename ${FILENAME})"
                echo "      contains a trailing newline and may not work as expected"
            fi
            cat "${SECRETFILE}" >"${FILESTRIP}"
            echo "[init-envfile] $(basename ${FILESTRIP}) set from $(basename ${FILENAME})"
        else
            echo "[init-envfile] cannot find secret in $(basename ${FILENAME})"
        fi
    done
fi
